name: Profile Auto-Update

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for local scripting only)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate dynamic blocks (no external API)
        shell: bash
        run: |
          set -euo pipefail

          # 1) Stats derived locally (approximation)
          COMMITS=$(git rev-list --count HEAD || echo 0)
          REPOS=$(ls -1d ../*/.git 2>/dev/null | wc -l | tr -d ' ' || echo 1)
          ISSUES=0
          PRS=0

          # 2) Wisdom rotation (local, no API)
          mapfile -t W < <(cat <<'EOF'
          Focus on craft; speed follows.
          Small, consistent steps compound massively.
          Automate the boring; create the meaningful.
          Clean pipelines, clean mind.
          Logs tell truths; listen.
          Shipping beats perfection.
          Test like a pessimist, build like an optimist.
          EOF
          )
          IDX=$(( ($(date +%s) / 21600) % ${#W[@]} )) # 6h buckets
          WISDOM="${W[$IDX]}"

          # 3) Tech stack scan (local repo summary)
          LANGS=$(git ls-files | awk -F. '/\./{print tolower($NF)}' | sort | uniq -c | sort -rn | awk '{printf "%s ", $2}')
          STACK_LIST="- Languages: ${LANGS:-markdown bash}
- DevOps: Git, GitHub Actions, Docker, Terraform, Kubernetes
- Cloud: AWS, GCP, Azure, Cloudflare
- Databases: PostgreSQL, MySQL, MongoDB, Redis
- Automation: Bash, Make, Ansible"

          # Safely update README markers
          README=README.md

          # Update STATS markers
          sed -i "/<!-- START:STATS/{:a;N;/<!-- END:STATS -->/!ba};s/<!-- START:STATS[\s\S]*<!-- END:STATS -->/<!-- START:STATS commits=${COMMITS} repos=${REPOS} issues=${ISSUES} prs=${PRS} -->\n<!-- END:STATS -->/" "$README"

          # Update WISDOM block text token
          sed -i "s/{{WISDOM_OF_THE_DAY}}.*/${WISDOM//\//\/}/" "$README" || true

          # Update TECH_STACK block
          awk -v repl="$STACK_LIST" '
            BEGIN{start=0}
            /<!-- START:TECH_STACK -->/{print;print repl;start=1;next}
            /<!-- END:TECH_STACK -->/{start=0}
            !start{print}
          ' "$README" > README.tmp && mv README.tmp "$README"

          echo "COMMITS=$COMMITS" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        shell: bash
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "chore(readme): auto-update stats, wisdom and stack"
          git push
